# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.scrapy.org/en/latest/topics/items.html

import scrapy


class StreammediaspiderItem(scrapy.Item):
    # define the fields for your item here like:
    # name = scrapy.Field()
    pass


# 新浪app
class SinaAppItem(scrapy.Item):
    pos = scrapy.Field()
    newsId = scrapy.Field()
    title = scrapy.Field()
    link = scrapy.Field()
    pic = scrapy.Field()
    showTag = scrapy.Field()
    articlePreload = scrapy.Field()
    commentStatus = scrapy.Field()
    adid = scrapy.Field()
    dislikeTags = scrapy.Field()
    parameter_id = scrapy.Field()


class ToutiaoAppItem(scrapy.Item):
    abstract = scrapy.Field()
    action_list = scrapy.Field()
    aggr_type = scrapy.Field()
    allow_download = scrapy.Field()
    article_sub_type = scrapy.Field()
    article_tpye = scrapy.Field()
    article_url = scrapy.Field()
    ban_comment = scrapy.Field()
    behot_time = scrapy.Field()
    bury_count = scrapy.Field()
    cell_flag = scrapy.Field()
    cell_layout_style = scrapy.Field()
    cell_type = scrapy.Field()
    comment_count = scrapy.Field()
    content_decoration = scrapy.Field()
    cursor = scrapy.Field()
    digg_count = scrapy.Field()
    display_url = scrapy.Field()
    filter_words = scrapy.Field()
    group_flags = scrapy.Field()
    group_id = scrapy.Field()
    has_video = scrapy.Field()
    hot = scrapy.Field()
    ignore_web_transform = scrapy.Field()
    is_subject = scrapy.Field()
    item_id = scrapy.Field()
    item_version = scrapy.Field()
    label = scrapy.Field()
    label_style = scrapy.Field()
    large_image_list = scrapy.Field()
    image = scrapy.Field()
    image_urls = scrapy.Field()
    level = scrapy.Field()
    log_pb = scrapy.Field()
    natant_level = scrapy.Field()
    preload_web = scrapy.Field()
    publish_time = scrapy.Field()
    raw_ad_data = scrapy.Field()
    read_count = scrapy.Field()
    repin_count = scrapy.Field()
    rid = scrapy.Field()
    share_count = scrapy.Field()
    share_info = scrapy.Field()
    share_url = scrapy.Field()
    show_dislike = scrapy.Field()
    show_portrait = scrapy.Field()
    show_portrait_article = scrapy.Field()
    source = scrapy.Field()
    source_avatar = scrapy.Field()
    tag = scrapy.Field()
    tag_id = scrapy.Field()
    title = scrapy.Field()
    url = scrapy.Field()
    user_repin = scrapy.Field()
    user_verified = scrapy.Field()
    video_detail_info = scrapy.Field()
    video_duration = scrapy.Field()
    video_id = scrapy.Field()
    video_play_info = scrapy.Field()
    video_proportion_article = scrapy.Field()
    video_style = scrapy.Field()
    parameter_id = scrapy.Field()


class SouhuAppItem(scrapy.Item):
    monitorkey = scrapy.Field()
    resource = scrapy.Field()
    resource2 = scrapy.Field()
    weight = scrapy.Field()
    itemspaceid = scrapy.Field()
    resource1 = scrapy.Field()
    impressionid = scrapy.Field()
    special = scrapy.Field()
    offline = scrapy.Field()
    adid = scrapy.Field()
    viewmonitor = scrapy.Field()
    size = scrapy.Field()
    online = scrapy.Field()
    position = scrapy.Field()
    tag = scrapy.Field()
    editNews = scrapy.Field()
    statsType = scrapy.Field()
    isPreload = scrapy.Field()
    newsType = scrapy.Field()
    gbcode = scrapy.Field()
    commentNum = scrapy.Field()
    isHasSponsorships = scrapy.Field()
    recomTime = scrapy.Field()
    newsId = scrapy.Field()
    iconNight = scrapy.Field()
    isWeather = scrapy.Field()
    isRecom = scrapy.Field()
    iconText = scrapy.Field()
    link = scrapy.Field()
    iconDay = scrapy.Field()
    abposition = scrapy.Field()
    adType = scrapy.Field()
    playTime = scrapy.Field()
    adp_type = scrapy.Field()
    isFlash = scrapy.Field()
    isHasTv = scrapy.Field()
    newschn = scrapy.Field()
    parameter_id = scrapy.Field()

class FenghuangAppItem(scrapy.Item):
    thumbnail = scrapy.Field()
    title = scrapy.Field()
    appSource = scrapy.Field()
    intro = scrapy.Field()
    adId = scrapy.Field()
    adPositionId = scrapy.Field()
    type = scrapy.Field()
    source = scrapy.Field()
    weburl = scrapy.Field()
    view = scrapy.Field()
    images = scrapy.Field()
    parameter_id =  scrapy.Field()

class TengxunxinwenAppItem(scrapy.Item):
    sub_type = scrapy.Field()
    oid = scrapy.Field()
    cid = scrapy.Field()
    soid = scrapy.Field()
    loc = scrapy.Field()
    stream_type = scrapy.Field()
    navTitle = scrapy.Field()
    shareTitle = scrapy.Field()
    resource_url0 = scrapy.Field()
    title = scrapy.Field()
    abstract = scrapy.Field()
    thumbnails = scrapy.Field()
    url = scrapy.Field()
    url_type = scrapy.Field()
    icon = scrapy.Field()
    pvLimit = scrapy.Field()
    pvFcs = scrapy.Field()
    comment = scrapy.Field()
    newsId = scrapy.Field()
    shareable = scrapy.Field()
    viewReportUrl = scrapy.Field()
    feedbackReportUrl = scrapy.Field()
    downloadReportUrl = scrapy.Field()
    advertiser_id = scrapy.Field()
    product_id = scrapy.Field()
    product_type = scrapy.Field()
    industry_id = scrapy.Field()
    icon_url = scrapy.Field()
    ping_data = scrapy.Field()
    click_data = scrapy.Field()
    extraReportUrl = scrapy.Field()
    parameter_id = scrapy.Field()

class ToutiaoxinwenAppItem(scrapy.Item):
    title = scrapy.Field()
    data_description = scrapy.Field()
    ad_id = scrapy.Field()
    url = scrapy.Field()
    publisher = scrapy.Field()
    img_url = scrapy.Field()
    parameter_id = scrapy.Field()

class QutoutiaoAppItem(scrapy.Item):
    pass